#!/bin/sh

options=$(bluetoothctl devices | awk '{print $NF}') 
choice=$(printf '%s\n' "$options" | dmenu -i)
devid=$(bluetoothctl devices | awk -v pattern="$choice" '$0 ~ pattern {print $2}')

if [ $choice ]; then
    bluetoothctl connect $devid 
fi