flip_status_indicators = true
volnorm = true
library_tabs = [ "playlists", "artists", "albums", "tracks", "podcasts" ]
use_nerdfont = true
shuffle = true
repeat = "playlist"
[track_format]
left = "%title - %artists "
center = ""
right = "%saved %duration"
